### ISSUE TITLE
[Openshift 4] - [ServiceAccount] : Token creation with ininity loop

### ISSUE THREAD

**Issue by lbourgeois76** [redhat-cop/namespace-configuration-operator#36] opened 2020-03-04 11:14 UTC
We have implemented in our openshift the use of the NS-configurator operator link to Service account (see the REAME exemple https://github.com/redhat-cop/namespace-configuration-operator#serviceaccount-with-special-permission).
In our case the namespace will contain a lot of secret token creation. These are created in infinity loop until crash our ETCD.

We are also using it to setup on our namspace TShifrt-size and Networkpolicy on the namspace without problem. But when we are activate the one with the serviceAccount this one become crazy.

For information:
Namespace Configuration Operator
0.1.0 provided by Containers & PaaS CoP

The Namespace Configuration are on the same namespace as the operator because in the documentation we don't see any information about it.

**Comment by lbourgeois76** [comment] 2020-03-04 11:25
With the operator log:
``` log
{"level":"info","ts":1583318434.8279483,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"controller_locked_object_/v1, Kind=ServiceAccount/test-token/special-sa"}
{"level":"info","ts":1583318434.8338308,"logger":"controller_locked_object","msg":"NewLockedObjectReconciler called on","type":"authorization.openshift.io/v1, Kind=RoleBinding","result":false,"value":null}
{"level":"error","ts":1583318434.8338714,"logger":"controller_locked_object","msg":"non-standard resources (without the spec field) are not supported","type":"authorization.openshift.io/v1, Kind=RoleBinding","error":"non-standard resources (without the spec field) are not supported","errorVerbose":"non-standard resources (without the spec field) are not supported\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/util.NewLockedObjectReconciler\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/util/locked-resource-reconciler.go:61\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).addManagedObject\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:529\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).applyConfigToNamespace\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:273\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).Reconcile\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/util.NewLockedObjectReconciler\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/util/locked-resource-reconciler.go:62\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).addManagedObject\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:529\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).applyConfigToNamespace\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:273\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).Reconcile\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1583318434.8339744,"logger":"controller_namespaceconfig","msg":"unable to create new NewLockedObjectReconciler on","object":{"apiVersion":"authorization.openshift.io/v1","groupNames":null,"kind":"RoleBinding","metadata":{"creationTimestamp":"2020-03-04T10:40:30Z","labels":{"namespace-config-operator.redhat-cop.io_owner":"namespace-configuration-operator-special-sa"},"name":"special-sa-registry-editor","namespace":"test-token","resourceVersion":"8214996","selfLink":"/apis/authorization.openshift.io/v1/namespaces/test-token/rolebindings/special-sa-registry-editor","uid":"91a0b499-5e04-11ea-b90e-06e22f312df2"},"roleRef":{"name":"registry-editor"},"subjects":[{"kind":"ServiceAccount","name":"special-sa"}],"userNames":["system:serviceaccount:test-token:special-sa"]},"error":"non-standard resources (without the spec field) are not supported","errorVerbose":"non-standard resources (without the spec field) are not supported\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/util.NewLockedObjectReconciler\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/util/locked-resource-reconciler.go:61\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).addManagedObject\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:529\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).applyConfigToNamespace\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:273\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).Reconcile\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).addManagedObject\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:531\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).applyConfigToNamespace\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:273\ngithub.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig.(*ReconcileNamespaceConfig).Reconcile\n\t/home/travis/gopath/src/github.com/redhat-cop/namespace-configuration-operator/pkg/controller/namespaceconfig/namespaceconfig_controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1583318434.9280987,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"controller_locked_object_/v1, Kind=ServiceAccount/test-token/special-sa","worker count":1}
{"level":"info","ts":1583318444.8420208,"logger":"controller_namespaceconfig","msg":"Reconciling NamespaceConfig","Request.Namespace":"namespace-configuration-operator","Request.Name":"special-sa"}
```

**Comment by raffaelespazzoli** [comment] 2020-05-06 18:16
@lbourgeois76 could you test again this issue with the current master?

**Comment by lbourgeois76** [comment] 2020-05-06 18:51
> @lbourgeois76 could you test again this issue with the current master?

Sorry i dont understand what exactly you want.
Did you change the version?
May i have to do something before?
May i give you more logs ? 
Or it is just To know if the problem is still here?

**Comment by raffaelespazzoli** [comment] 2020-05-06 19:09
@lbourgeois76 I'm in the process of releasing a new version that will add some features that were highly requested. It will also sightly change the CRD (sorry).
It should be out on operatohub in the next few days. In the meantime you can try the new version with the helm-based deployment.
I was asking you if you could see of the error is still there with the new version.

**Comment by lbourgeois76** [comment] 2020-05-06 19:55
Ok. I Will see with my collegues tomorrow if  we can do it as soon as possible. 
Any prerequisit?
Openshift version ? Environnement version?
Which is the link (tag) of the version to test?

**Comment by raffaelespazzoli** [comment] 2020-05-07 01:35
`Any prerequisit?`

none besides normal operator suff.

`Openshift version ?` 

I tested only in 4.x, but I don't see why it wouldn't work in OCP 3.x. I also added support for kuberneets.

`Environnement version?`

not sure what you mean here.

`Which is the link (tag) of the version to test?`

v0.2.0, but please read the new docs before just updating the image tag.

**Comment by raffaelespazzoli** [comment] 2020-07-28 00:35
@lbourgeois76 may I close this issue?

**Comment by kahootali** [comment] 2020-08-04 06:03
I am also facing same issue...
Openshift 4.5.4
Namespace Config Operator: 0.2.1

Created a NamespaceConfig with ServiceAccount, when namespace was created, it went into an infinite loop, creating new secrets and reloading SA. It created 1000s of secrets

**Comment by rasheedamir** [comment] 2020-08-04 09:45
@raffaelespazzoli we can make the PR for this change if you can guide us where the issue could be; this issue is blocking us

**Comment by raffaelespazzoli** [comment] 2020-08-04 11:14
@kahootali I tested this morning the with the example on the repo (https://github.com/redhat-cop/namespace-configuration-operator/tree/master/examples/namespace-config#serviceaccount-with-special-permission) and everything seems fine. I cannot reproduce this issue.
I have not tried though with explicitly adding secrets to the service account. Can you try to ignore the secrets in the reconcile loop, but adding:
```
    - objectTemplate: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: sa-name
          namespace: {{ .Name }}
        secrets:
          - name: secret1
          - name: secret2
      excludedPaths:
      - .secrets
```

@rasheedamir you are welcome to contribute a fix. I don't know how to guide you because I cannot see the error. More useful probably would be if you can spell the exact steps that reproduce the error.

**Comment by kahootali** [comment] 2020-08-04 14:55
@raffaelespazzoli Yeah it worked by adding the excludedPaths, can you please tell what `excludedPaths` field does for our understanding?

**Comment by raffaelespazzoli** [comment] 2020-08-04 15:09
@kahootali  please see the docs: https://github.com/redhat-cop/namespace-configuration-operator#excluded-paths

**Closed** 2020-09-01 10:33 UTC
