### ISSUE TITLE
Dynamically create a ServiceAccount and RoleBinding using the namespace name

### ISSUE THREAD

**Issue by D1abloRUS** [redhat-cop/namespace-configuration-operator#20] opened 2019-10-31 11:52 UTC
is it possible?

**Comment by raffaelespazzoli** [comment] 2019-10-31 12:27
@D1abloRUS if you mean that the created ServiceAccount and RoleBinding should be somehow parametric on the namespace name, then no it is not possible at the moment because there is no support for templating.

**Comment by D1abloRUS** [comment] 2019-10-31 12:42
@raffaelespazzoli it would be great

**Comment by raffaelespazzoli** [comment] 2019-11-05 13:36
do you want to be able to name the service account and the role binding based on the namespace name? That would be difficult because the resource name is a key used by the operator to retrieve the resource at the later time and compare it with the desired state.
Adding the logic to support renaming resources it's probably possible (I'd have to think about it) but it would make the operator logic way more complex.
What you case are you trying to address?

**Comment by raffaelespazzoli** [comment] 2020-04-15 11:06
Duplicate of #29 
Duplicate of #28

**Comment by raffaelespazzoli** [comment] 2020-05-06 18:13
this has been closed with #37

**Closed by raffaelespazzoli** 2020-05-06 18:13 UTC
